[workspace]
members = [
    "crates/floe-node",
    "crates/floe-config",
    "crates/floe-node-core",
    "crates/floe-cdc",
    "crates/floe-cdc-core",
    "crates/floe-cdc-pg",
    "crates/floe-core",
    "crates/floe-executor",
    "crates/floe-benchmarks",
    "crates/floe-server",
    "crates/floe-storage",
    "crates/dbsp",
    "crates/dbsp-semantic",
    "crates/dbsp-runtime",
    "crates/dbsp-storage",
    "crates/dbsp-circuit",
    "crates/dbsp-planner",
    "crates/floe-sql-parser",
]
default-members = ["crates/floe-node"]
resolver = "3"

[workspace.package]
edition = "2024"

[workspace.dependencies]
ahash = "0.8"
arc-swap = "1.7"
anyhow = "1.0"
async-recursion = "1.0"
async-trait = "0.1"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
bytes = "1"
clap = { version = "4.5", features = ["derive"] }
datafusion = "52.1.0"
datafusion-common = "52.1.0"
datafusion-sql = "52.1.0"
axum = "0.7"
futures = "0.3"
hashbrown = "0.15"
nexmark = { version = "0.2.0", features = ["serde"] }
object_store = "0.12.4"
pgwire = { version = "0.38.0", default-features = false, features = ["server-api-ring", "pg-ext-types"] }
postgres-protocol = "0.6"
postgres-types = "0.2"
pgwire-replication = { version = "0.3.2", default-features = false, features = ["scram"] }
rkyv = "0.8.12"
rdkafka = { version = "0.36", features = ["tokio", "cmake-build"] }
rayon = "1.10"
arrow-array = "57.1.0"
arrow-ipc = { version = "57.1.0", features = ["lz4"] }
arrow-schema = "57.1.0"
arrow-pg = { version = "0.12.1", default-features = false, features = ["datafusion"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
slatedb = { version = "0.13.1", default-features = false }
sqlparser = "0.59"
tokio = { version = "1.38", features = ["full"] }
tokio-util = "0.7"
tokio-postgres = "0.7"
toml = "0.8"
url = "2.5"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
floe-sql-parser = { path = "crates/floe-sql-parser" }
floe-config = { path = "crates/floe-config" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
prometheus = "0.13"
