[package]
name = "dbsp-runtime"
version = "0.1.0"
edition.workspace = true

[dependencies]
dbsp-storage = { path = "../dbsp-storage" }
ahash = { workspace = true }
anyhow = { workspace = true }
arrow-array = { workspace = true }
arrow-ipc = { workspace = true }
arrow-ord = { workspace = true }
arrow-schema = { workspace = true }
arrow-select = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
hashbrown = { workspace = true }
rkyv = { workspace = true }
serde = { workspace = true }
slatedb = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
prometheus = { workspace = true }

[dev-dependencies]
bytes = { workspace = true }
object_store = { workspace = true }
