[package]
name = "floe-executor"
version = "0.1.0"
edition.workspace = true

[dependencies]
floe-core = { path = "../floe-core" }
floe-storage = { path = "../floe-storage" }
dbsp = { path = "../dbsp" }
anyhow = { workspace = true }
async-recursion = { workspace = true }
async-trait = { workspace = true }
datafusion = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
slatedb = { workspace = true }
object_store = { workspace = true }

[dev-dependencies]
arrow-schema = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
