[package]
name = "floe-executor"
version = "0.1.0"
edition.workspace = true

[dependencies]
ahash = { workspace = true }
arc-swap = { workspace = true }
floe-core = { path = "../floe-core" }
floe-storage = { path = "../floe-storage" }
dbsp = { path = "../dbsp" }
floe-sql-parser = { path = "../floe-sql-parser" }
arrow-ipc = "57.1.0"
anyhow = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
datafusion = { workspace = true }
datafusion-sql = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlparser = { workspace = true }
slatedb = { workspace = true }
object_store = { workspace = true }
tokio = { workspace = true, features = ["sync", "net", "rt", "io-util"] }
tokio-util = { workspace = true }
tracing = { workspace = true }
prometheus = { workspace = true }
xxhash-rust = { version = "0.8", features = ["xxh3"] }

[dev-dependencies]
arrow-schema = { workspace = true }
nexmark = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
