[package]
name = "floe-benchmarks"
version = "0.1.0"
edition.workspace = true

[dev-dependencies]
async-trait = { workspace = true }
criterion = "0.5"
datafusion = { workspace = true }
dbsp = { path = "../dbsp" }
floe-executor = { path = "../floe-executor" }
parking_lot = "0.12"
rkyv = { workspace = true }
tokio = { workspace = true }

[[bench]]
name = "rkyv_arrow_datafusion"
harness = false
