[package]
name = "floe-benchmarks"
version = "0.1.0"
edition.workspace = true

[features]
default = []
allocator-mimalloc = ["dep:mimalloc"]
allocator-jemalloc = ["dep:tikv-jemallocator"]

[dependencies]
anyhow = { workspace = true }
floe-executor = { path = "../floe-executor" }
floe-node-core = { path = "../floe-node-core" }
floe-sql-parser = { path = "../floe-sql-parser" }
slatedb = { workspace = true, features = ["aws"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
rdkafka = { workspace = true }
mimalloc = { version = "0.1", optional = true, default-features = false }
tikv-jemallocator = { version = "0.6", optional = true }

[dev-dependencies]
async-trait = { workspace = true }
criterion = "0.5"
datafusion = { workspace = true }
dbsp = { path = "../dbsp" }
parking_lot = "0.12"
rkyv = { workspace = true }
arrow-ipc = "57.1.0"
object_store = { workspace = true }
slatedb = { workspace = true }

[[bench]]
name = "rkyv_arrow_datafusion"
harness = false

[[bench]]
name = "rkyv_arrow_ipc_storage"
harness = false

[[bench]]
name = "update_model_storage"
harness = false
