[package]
name = "floe-node"
version = "0.1.0"
edition.workspace = true

[dependencies]
floe-core = { path = "../floe-core" }
floe-executor = { path = "../floe-executor" }
floe-storage = { path = "../floe-storage" }
dbsp = { path = "../dbsp" }
anyhow = { workspace = true }
async-trait = { workspace = true }
datafusion = { workspace = true }
datafusion-common = { workspace = true }
futures = { workspace = true }
clap = { workspace = true }
nexmark = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
pgwire = { workspace = true }
sqlparser = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
floe-sql-parser = { workspace = true }
slatedb = { workspace = true }
bytes = "1.6"
postgres-types = { version = "0.2", features = ["with-chrono-0_4"] }
chrono = { workspace = true }

[dev-dependencies]
arrow-schema = { workspace = true }
arrow-array = "56.2.0"
arrow-buffer = "56.2.0"
arrow-data = "56.2.0"
tempfile = "3.10"
tokio-postgres = { version = "0.7", features = ["runtime"] }
