[package]
name = "floe-node"
version = "0.1.0"
edition.workspace = true

[dependencies]
floe-executor = { path = "../floe-executor" }
floe-node-core = { path = "../floe-node-core" }
floe-server = { path = "../floe-server" }
dbsp = { path = "../dbsp" }
anyhow = { workspace = true }
datafusion = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
floe-sql-parser = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
slatedb = { workspace = true }
floe-storage = { path = "../floe-storage" }
arrow-schema = { workspace = true }
arrow-array = "56.2.0"
arrow-buffer = "56.2.0"
arrow-data = "56.2.0"
tempfile = "3.10"
tokio-postgres = { version = "0.7", features = ["runtime"] }
