[package]
name = "floe-storage"
version = "0.1.0"
edition.workspace = true

[dependencies]
floe-cdc-core = { path = "../floe-cdc-core" }
floe-core = { path = "../floe-core" }
anyhow = { workspace = true }
arrow-ipc = "57.1.0"
arrow-schema = { workspace = true }
futures = { workspace = true }
object_store = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
slatedb = { workspace = true }
tokio = { workspace = true }
