[package]
name = "floe-cdc-pg"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
floe-cdc = { path = "../floe-cdc" }
floe-cdc-core = { path = "../floe-cdc-core" }
floe-core = { path = "../floe-core" }
pgwire-replication = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
dbsp-storage = { path = "../dbsp-storage" }
object_store = { workspace = true }
serde_json = { workspace = true }
slatedb = { workspace = true }
